### ISSUE TITLE
Issue-Invoke super.paintComponent

### ISSUE THREAD

**Issue by LeeDongGeon1996** [k33ptoo/KControls#2]
Hi, I also found another problem in KButton.java.

> Before performing any custom painting, the component paints its background by invoking super.paintComponent. If we remove that call, either our custom painting code must paint the component's background or we must invoke setOpaque(false) on the component. Doing the latter would inform the Swing painting system that the components behind the non-opaque component might be visible, and thus should be painted.

```
@Override
    protected void paintComponent(Graphics g) {
    	
    	//Suggestion code.
    	//super.paintComponent(g);
    	//super.setContentAreaFilled(false);
    	
        Graphics2D g2 = (Graphics2D) g.create();
        g2.setRenderingHint(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY);
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        
...
```

It cause the problem that the background of JButton will be painted after another component's event.
Like this,
![캡처](https://user-images.githubusercontent.com/38756230/57873744-ea723180-7806-11e9-9290-1e56df6ab39b.PNG)

So I suggest you to add below two lines at the top of `paintComponent(Graphics g) `.
```
super.paintComponent(g);
super.setContentAreaFilled(false);
```
This is also tested and I found it works well.

See the details in https://www.cs.tut.fi/lintula/manual/java/tutorial/uiswing/painting/overview.html

**Comment by k33ptoo** [comment]
Thank you Mahmoud and Lee for this.
